### ISSUE TITLE
Make LoginOverLay more configurable

### ISSUE THREAD

**Issue by haiwan** [vaadin/vaadin-login#96]
Would it worth to have LoginOverlay more configurable? e.g. user might want to add more components to the login view, like a dropdown for domain/realm

**Comment by kolle1986** [comment]
Still nothing on this?

**Comment by OlliTietavainenVaadin** [comment]
Use case: adding a "register" button for users who don't have an account yet

**Comment by mlindfors** [comment]
Use case: adding a CAPTCHA on the overlay.

**Comment by kolle1986** [comment]
Still nothing on this?

**Comment by web-padawan** [comment]
This is not currently prioritised. 

Also, the teleportation logic is a bit awkward at the moment. We might change that in future while migrating to LitElement so implement that in a more straightforward way.

The overall concept of "teleportation" is unlikely to be changed though, as the root problem it addresses is that password managers are unable to deal with `<input>` tags in Shadow DOM.

Technically, it should be possible to extend `vaadin-login-overlay` and override this method:

https://github.com/vaadin/vaadin-login/blob/f592dc38ad124da91845881fd9d3a550c5b1b537/src/vaadin-login-overlay.html#L179-L181

This would also require to add another `<slot>` to `vaadin-login-form-wrapper`. Or you could use `title` slot and then some CSS tweaks to put added content to different place.

**Comment by lyonkwa** [comment]
I would also be great to make the footer customizable. The `i18n.setAdditionalInformation ` only accept a String as parameter. It should accept a component like the header.

**Comment by simasch** [comment]
Use case: Remember me

**Comment by thigg** [comment]
Use case: Login consisting of more fields than just username and password

**Comment by mvysny** [comment]
Use-case: custom login form mimicking the old one when migrating app from Vaadin 8 to Vaadin 14.

**Comment by mvysny** [comment]
Meanwhile, how to create a custom login form:

Create a component emitting `<form>` element:

```java
@Tag("form")
public class FormComponent extends Component implements HasComponents, HasSize, HasStyle {
    public FormComponent() {
        setId("loginForm");
        getElement().setAttribute("method", "post");
        getElement().setAttribute("autocomplete", "on");
    }
}
```

Add the username/password fields to it. Use `Input` instead of `TextField`:

```java
		userNameField.setWidth("100%");
		userNameField.setId("username");
		userNameField.getElement().setAttribute("autocomplete", "username");
		userNameField.getClassNames().add("login-textfield");
//		userNameField.setPrefixComponent(new Icon(VaadinIcon.USER));

		passwordField.setWidth("100%");
		passwordField.setId("password");
		passwordField.getElement().setAttribute("autocomplete", "current-password");
		passwordField.getElement().setAttribute("type", "password");
		passwordField.getClassNames().add("login-textfield");
```

Add a nice styling:

```css
.login-textfield {
  appearance: none;
  user-select: text;
  margin: 0;
  font: inherit;
  font-weight: 400;
  line-height: normal;
  height: 20px;
  border-radius: 4px;
  padding: 3px 7px;
  border: 1px solid #c9c9c9;
  background: white;
  color: #474747;
  width: 185px;
}

.login-textfield:focus {
  outline: none;
  border-color: #00506A;
}
```
